services:
  # database
  postgres_db:
    image: postgres:18-alpine
    container_name: club_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: typescript
      POSTGRES_DB: club_management
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    profiles:
      - dev
  # development
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dev:latest
    container_name: club_panel_dev
    ports:
      - '8000:3000'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - TZ=Asia/Tehran
    depends_on:
      - postgres_db
    profiles:
      - dev
  # production
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: prod:latest
    container_name: club_panel_prod
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - TZ=Asia/Tehran
    profiles:
      - prod

volumes:
  postgres_data: