services:
  # development
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dev:latest
    container_name: club_panel_dev
    ports:
      - "8000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    profiles:
      - dev
  # production
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: prod:latest
    container_name: club_panel_prod
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    profiles:
      - prod
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-prod
    profiles:
      - prod
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
