FROM node:22-alpine AS Development

# enable corepack pnpm
RUN corepack enable && corepack prepare pnpm --activate

# set the worker directory inside the container
WORKDIR /app

# install postgresql
RUN apk add --no-cache postgresql-client

COPY package*.json pnpm*.yaml ./

# install package
RUN pnpm install

# copy the  rest of the application
COPY . .

# port the app runs on
EXPOSE 3000

# Command to run the app
CMD [ "pnpm", "start:dev" ]