version: '3.8'

services:
  app:
    container_name: club_panel_nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
