worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    include mime.types;
    default_type application/octet-stream;

    keepalive_timeout 65;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_vary on;

    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=60s use_temp_path=off;

    upstream nest_backend {
        server app-prod:3000;
        keepalive 32;
    }

    server {
        listen 80;
        server_name api.e4f.ir www.api.e4f.ir;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name api.e4f.ir www.api.e4f.ir;

        ssl_certificate /etc/letsencrypt/live/api.e4f.ir/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.e4f.ir/privkey.pem;

        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        add_header X-Frame-Options SAMEORIGIN always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy no-referrer-when-downgrade always;

        location /uploads/ {
            alias /app/uploads/;

            add_header Access-Control-Allow-Origin "*" always;
            add_header Cross-Origin-Resource-Policy "cross-origin" always;

            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        location / {
            proxy_pass http://nest_backend;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            send_timeout 60s;

            proxy_buffering on;
            proxy_buffers 16 16k;
            proxy_buffer_size 32k;

            proxy_cache my_cache;
            proxy_cache_methods GET HEAD;
            proxy_cache_valid 200 30s;
            proxy_cache_bypass $http_authorization;
            proxy_no_cache $http_authorization;
        }
    }
}
